os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc-9.3
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Call your build system
  - sudo chmod +x build.sh 
  - sudo ./build.sh 1.9.1 Release
