#
# MongoDB Plugin - A plugin for Orthanc DICOM Server for storing DICOM data in MongoDB Database
# Copyright (C) 2017 - 2026  (Doc Cirrus GmbH)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

cmake_minimum_required(VERSION 3.15...4.0)
project(OrthancMongoDB)

# The version of this plugin follows the version of the Orthanc core it targets
set(ORTHANC_PLUGIN_VERSION "1.13.0")

# This is the preferred version of the Orthanc SDK for this plugin
set(ORTHANC_SDK_DEFAULT_VERSION "1.13.0")

# This is the list of the versions of the Orthanc SDK against which
# this plugin will compile
set(ORTHANC_SDK_COMPATIBLE_VERSIONS "1.13.0")

# This is the minimal version of the Orthanc runtime that will provide
# best performance. If the version of the Orthanc runtime is below
# this minimal version, a warning message will be printed (but the
# plugin will still start).
set(ORTHANC_OPTIMAL_VERSION_MAJOR    1)
set(ORTHANC_OPTIMAL_VERSION_MINOR    13)
set(ORTHANC_OPTIMAL_VERSION_REVISION 0)

if (ORTHANC_PLUGIN_VERSION STREQUAL "mainline")
  set(ORTHANC_FRAMEWORK_VERSION "mainline")
  set(ORTHANC_FRAMEWORK_DEFAULT_SOURCE "hg")
else()
  set(ORTHANC_FRAMEWORK_VERSION "1.13.0")
  set(ORTHANC_FRAMEWORK_DEFAULT_SOURCE "web")
endif()

set(BUILD_TESTS ON CACHE BOOL "Build the unit tests")

include(${CMAKE_SOURCE_DIR}/../Resources/CMake/DatabasesPluginParameters.cmake)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include(${CMAKE_SOURCE_DIR}/../Resources/CMake/DatabasesPluginConfiguration.cmake)


if (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
  execute_process(
    COMMAND
    ${PYTHON_EXECUTABLE} ${ORTHANC_FRAMEWORK_ROOT}/../Resources/WindowsResources.py
    ${ORTHANC_PLUGIN_VERSION} "MongoDB storage area plugin" OrthancMongoDBStorage.dll
    "MongoDB as a database back-end to Orthanc (storage area)"
    ERROR_VARIABLE Failure
    OUTPUT_FILE ${AUTOGENERATED_DIR}/StorageVersion.rc
    )

  if (Failure)
    message(FATAL_ERROR "Error while computing the version information: ${Failure}")
  endif()

  execute_process(
    COMMAND
    ${PYTHON_EXECUTABLE} ${ORTHANC_FRAMEWORK_ROOT}/../Resources/WindowsResources.py
    ${ORTHANC_PLUGIN_VERSION} "MongoDB index plugin" OrthancMongoDBIndex.dll
    "MongoDB as a database back-end to Orthanc (index)"
    ERROR_VARIABLE Failure
    OUTPUT_FILE ${AUTOGENERATED_DIR}/IndexVersion.rc
    )

  if (Failure)
    message(FATAL_ERROR "Error while computing the version information: ${Failure}")
  endif()

  set(INDEX_RESOURCES ${AUTOGENERATED_DIR}/IndexVersion.rc)
  set(STORAGE_RESOURCES ${AUTOGENERATED_DIR}/StorageVersion.rc)
endif()


if (EXISTS ${ORTHANC_SDK_ROOT}/orthanc/OrthancDatabasePlugin.proto)
  add_custom_command(
    COMMAND
    ${PROTOC_EXECUTABLE} ${ORTHANC_SDK_ROOT}/orthanc/OrthancDatabasePlugin.proto --cpp_out=${AUTOGENERATED_DIR} -I${ORTHANC_SDK_ROOT}/orthanc/
    DEPENDS
    ProtobufCompiler
    ${ORTHANC_SDK_ROOT}/orthanc/OrthancDatabasePlugin.proto
    OUTPUT
    ${AUTOGENERATED_DIR}/OrthancDatabasePlugin.pb.cc
    ${AUTOGENERATED_DIR}/OrthancDatabasePlugin.pb.h
    )

  list(APPEND AUTOGENERATED_SOURCES
    ${AUTOGENERATED_DIR}/OrthancDatabasePlugin.pb.cc
    )
endif()


add_custom_target(
  AutogeneratedTarget
  DEPENDS
  ${AUTOGENERATED_SOURCES}
  )

set(MONGODB_PLUGINS_SOURCES
  Plugins/Index/MongoDBAttachments.cpp
  Plugins/Index/MongoDBAuditLogs.cpp
  Plugins/Index/MongoDBChanges.cpp
  Plugins/Index/MongoDBExportedResources.cpp
  Plugins/Index/MongoDBFind.cpp
  Plugins/Index/MongoDBGlobalProperties.cpp
  Plugins/Index/MongoDBKeyValueStores.cpp
  Plugins/Index/MongoDBLabels.cpp
  Plugins/Index/MongoDBLookup.cpp
  Plugins/Index/MongoDBMainDicomTags.cpp
  Plugins/Index/MongoDBMetadata.cpp
  Plugins/Index/MongoDBPatientRecycling.cpp
  Plugins/Index/MongoDBQueues.cpp
  Plugins/Index/MongoDBResources.cpp
  Plugins/Index/MongoDBStatistics.cpp
  Plugins/MongoDBIndex.cpp
  Plugins/MongoDBSchema.cpp
  Plugins/MongoDBStorageArea.cpp
  )

add_library(FrameworkForPlugins STATIC
  ${AUTOGENERATED_SOURCES}
  ${DATABASES_SOURCES}
  ${ORTHANC_DATABASES_ROOT}/Framework/Plugins/PluginInitialization.cpp
  ${MONGODB_PLUGINS_SOURCES}
  )

set_target_properties(FrameworkForPlugins PROPERTIES
  POSITION_INDEPENDENT_CODE ON
  COMPILE_FLAGS -DORTHANC_ENABLE_LOGGING_PLUGIN=1
  )

add_library(OrthancMongoDBIndex SHARED
  ${INDEX_RESOURCES}
  Plugins/IndexPlugin.cpp
  )

add_library(OrthancMongoDBStorage SHARED
  ${STORAGE_RESOURCES}
  Plugins/StoragePlugin.cpp
  )

add_dependencies(FrameworkForPlugins AutogeneratedTarget)

target_link_libraries(OrthancMongoDBIndex FrameworkForPlugins)
target_link_libraries(OrthancMongoDBStorage FrameworkForPlugins)

message("Setting the version of the libraries to ${ORTHANC_PLUGIN_VERSION}")

add_definitions(
  -DORTHANC_PLUGIN_VERSION="${ORTHANC_PLUGIN_VERSION}"
  )

set_target_properties(OrthancMongoDBStorage PROPERTIES
  VERSION ${ORTHANC_PLUGIN_VERSION}
  SOVERSION ${ORTHANC_PLUGIN_VERSION}
  COMPILE_FLAGS -DORTHANC_ENABLE_LOGGING_PLUGIN=1
  )

set_target_properties(OrthancMongoDBIndex PROPERTIES
  VERSION ${ORTHANC_PLUGIN_VERSION}
  SOVERSION ${ORTHANC_PLUGIN_VERSION}
  COMPILE_FLAGS -DORTHANC_ENABLE_LOGGING_PLUGIN=1
  )


install(
  TARGETS OrthancMongoDBIndex OrthancMongoDBStorage
  RUNTIME DESTINATION lib    # Destination for Windows
  LIBRARY DESTINATION share/orthanc/plugins    # Destination for Linux
  )


if (BUILD_TESTS)
  add_executable(UnitTests
    ${MONGODB_PLUGINS_SOURCES}
    UnitTests/MongoDBTests.cpp
    UnitTests/MongoDBTestsToolbox.cpp
    UnitTests/UnitTestsMain.cpp
    ${DATABASES_SOURCES}
    ${GOOGLE_TEST_SOURCES}
    ${AUTOGENERATED_SOURCES}
    )

  add_dependencies(UnitTests AutogeneratedTarget)

  target_link_libraries(UnitTests ${GOOGLE_TEST_LIBRARIES})
  set_target_properties(UnitTests PROPERTIES
    COMPILE_FLAGS -DORTHANC_ENABLE_LOGGING_PLUGIN=0
    )
endif()


if (COMMAND DefineSourceBasenameForTarget)
  DefineSourceBasenameForTarget(FrameworkForPlugins)
  DefineSourceBasenameForTarget(OrthancMongoDBIndex)
  DefineSourceBasenameForTarget(OrthancMongoDBStorage)
  if (BUILD_TESTS)
    DefineSourceBasenameForTarget(UnitTests)
  endif()
endif()
