/**
 * MongoDB Plugin - A plugin for Orthanc DICOM Server for storing DICOM data in MongoDB Database
 * Copyright (C) 2017 - 2026  (Doc Cirrus GmbH)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/


#include "MongoDBSchema.h"

#include "Index/MongoDBGlobalProperties.h"
#include "Index/MongoDBStatistics.h"
#include "../../Framework/MongoDB/MongoDBDatabase.h"
#include "../../Framework/Plugins/GlobalProperties.h"

#include <Logging.h>
#include <OrthancException.h>
#include <Toolbox.h>

#include <boost/lexical_cast.hpp>
#include <boost/thread.hpp>

#include <atomic>
#include <map>
#include <vector>


namespace OrthancDatabases
{
  using bsoncxx::builder::basic::kvp;
  using bsoncxx::builder::basic::make_array;
  using bsoncxx::builder::basic::make_document;


  namespace
  {
    struct IndexDefinition
    {
      std::string               collection_;
      bsoncxx::document::value  keys_;
      bool                      unique_;

      IndexDefinition(const std::string& collection,
                      const bsoncxx::document::value& keys,
                      bool unique) :
        collection_(collection),
        keys_(keys),
        unique_(unique)
      {
      }

      /**
       * The ordinary indexes keep the name generated by MongoDB, as in
       * the previous versions of the plugin, which create them at each
       * startup. A unique index gets its own name: the previous
       * versions still find their ordinary index on the same keys
       * (creating an index whose name already exists with other options
       * fails), and they never break the unique constraint.
       **/
      std::string GetName() const
      {
        std::string name;
        for (const bsoncxx::document::element& key : keys_.view())
        {
          if (!name.empty())
          {
            name += "_";
          }
          name += std::string(key.key()) + "_1";
        }

        return (unique_ ? name + "_unique" : name);
      }

      std::string GetDescription() const
      {
        return collection_ + "." + GetName();
      }
    };
  }


  static std::vector<IndexDefinition> GetIndexes()
  {
    std::vector<IndexDefinition> indexes;

    // Revision 1 (the previous versions of the plugin)
    indexes.emplace_back("fs.files", make_document(kvp("filename", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("parentId", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("publicId", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("resourceType", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("internalId", 1)), false);
    indexes.emplace_back("PatientRecyclingOrder", make_document(kvp("patientId", 1)), false);
    indexes.emplace_back("MainDicomTags", make_document(kvp("id", 1)), false);
    indexes.emplace_back("MainDicomTags", make_document(kvp("tagGroup", 1), kvp("tagElement", 1), kvp("value", 1)), false);
    indexes.emplace_back("DicomIdentifiers", make_document(kvp("id", 1)), false);
    indexes.emplace_back("DicomIdentifiers", make_document(kvp("tagGroup", 1), kvp("tagElement", 1), kvp("value", 1)), false);
    indexes.emplace_back("Changes", make_document(kvp("internalId", 1)), false);
    indexes.emplace_back("AttachedFiles", make_document(kvp("id", 1)), false);
    indexes.emplace_back("Metadata", make_document(kvp("id", 1)), false);
    indexes.emplace_back("GlobalProperties", make_document(kvp("property", 1)), false);
    indexes.emplace_back("ServerProperties", make_document(kvp("server", 1), kvp("property", 1)), false);

    // Revision 2: the level arrays "0" to "3" (multikey), for
    // "AttachChild()" and for the candidates of "LookupResources()"
    indexes.emplace_back("Resources", make_document(kvp("0", 1), kvp("resourceType", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("1", 1), kvp("resourceType", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("2", 1), kvp("resourceType", 1)), false);
    indexes.emplace_back("Resources", make_document(kvp("3", 1), kvp("resourceType", 1)), false);

    // Revision 2: the correlated "$lookup" of "LookupResources()"
    indexes.emplace_back("MainDicomTags", make_document(kvp("id", 1), kvp("tagGroup", 1), kvp("tagElement", 1)), false);
    indexes.emplace_back("DicomIdentifiers", make_document(kvp("id", 1), kvp("tagGroup", 1), kvp("tagElement", 1)), false);

    // Revision 2: the resources of a level in the order of their public
    // IDs, for the pages of "ExecuteFind()" without ordering ("internalId"
    // makes the scan covered, when no other field is needed)
    indexes.emplace_back("Resources", make_document(kvp("resourceType", 1), kvp("publicId", 1), kvp("internalId", 1)), false);

    // Revision 2: the sequence field of the ordered collections, and
    // the attachments by UUID
    indexes.emplace_back("Changes", make_document(kvp("id", 1)), false);
    indexes.emplace_back("ExportedResources", make_document(kvp("id", 1)), false);
    indexes.emplace_back("PatientRecyclingOrder", make_document(kvp("id", 1)), false);
    indexes.emplace_back("AttachedFiles", make_document(kvp("uuid", 1)), false);

    // Revision 2: the unique indexes, that make the upserts safe on a
    // standalone server (without them, two concurrent upserts can both
    // insert a document)
    indexes.emplace_back("Resources", make_document(kvp("publicId", 1)), true);
    indexes.emplace_back("Resources", make_document(kvp("internalId", 1)), true);
    indexes.emplace_back("Sequences", make_document(kvp("name", 1)), true);
    indexes.emplace_back("GlobalProperties", make_document(kvp("property", 1)), true);
    indexes.emplace_back("ServerProperties", make_document(kvp("server", 1), kvp("property", 1)), true);
    indexes.emplace_back("AttachedFiles", make_document(kvp("id", 1), kvp("fileType", 1)), true);
    indexes.emplace_back("Metadata", make_document(kvp("id", 1), kvp("type", 1)), true);

    // Revision 2: the labels, by resource (unique) and by name
    indexes.emplace_back("Labels", make_document(kvp("id", 1), kvp("label", 1)), true);
    indexes.emplace_back("Labels", make_document(kvp("label", 1), kvp("id", 1)), false);

    // Revision 2: the key-value stores (unique) and the queues, in their order
    indexes.emplace_back("KeyValueStores", make_document(kvp("storeId", 1), kvp("key", 1)), true);
    indexes.emplace_back("Queues", make_document(kvp("queueId", 1), kvp("id", 1)), false);

    // Revision 2: the audit logs, in chronological order (the index on
    // "ts" is a TTL index if "AuditLogsRetentionDays" is set)
    indexes.emplace_back("AuditLogs", make_document(kvp("ts", 1)), false);
    indexes.emplace_back("AuditLogs", make_document(kvp("userId", 1), kvp("ts", 1)), false);
    indexes.emplace_back("AuditLogs", make_document(kvp("resourceId", 1), kvp("ts", 1)), false);
    indexes.emplace_back("AuditLogs", make_document(kvp("action", 1), kvp("ts", 1)), false);

    return indexes;
  }


  static bool IsUniqueIndex(const bsoncxx::document::view& index)
  {
    bsoncxx::document::element unique = index["unique"];
    return (unique && unique.type() == bsoncxx::type::k_bool && unique.get_bool().value);
  }


  static bool IsAscending(const bsoncxx::document::element& key)
  {
    // The value 1 may be stored as an int32, an int64 or a double
    switch (key.type())
    {
      case bsoncxx::type::k_int32:
        return key.get_int32().value == 1;

      case bsoncxx::type::k_int64:
        return key.get_int64().value == 1;

      case bsoncxx::type::k_double:
        return key.get_double().value == 1.0;

      default:
        return false;
    }
  }


  static bool HasSameKeys(const bsoncxx::document::view& existing,
                          const bsoncxx::document::view& definition)
  {
    // The order of the keys matters. All the defined indexes are ascending.
    bsoncxx::document::view::const_iterator i = existing.begin();
    bsoncxx::document::view::const_iterator j = definition.begin();

    while (i != existing.end() && j != definition.end())
    {
      if (i->key() != j->key() ||
          !IsAscending(*i))
      {
        return false;
      }

      ++i;
      ++j;
    }

    return (i == existing.end() && j == definition.end());
  }


  namespace
  {
    // The indexes that exist in the database, by collection
    class ExistingIndexes : public boost::noncopyable
    {
    private:
      mongocxx::database&                                           database_;
      std::map<std::string, std::vector<bsoncxx::document::value> > content_;

      const std::vector<bsoncxx::document::value>& GetCollection(const std::string& collection)
      {
        std::map<std::string, std::vector<bsoncxx::document::value> >::const_iterator found = content_.find(collection);
        if (found != content_.end())
        {
          return found->second;
        }

        std::vector<bsoncxx::document::value>& indexes = content_[collection];

        try
        {
          // "listIndexes" on a collection that does not exist yet lists nothing
          mongocxx::cursor cursor = database_[collection].list_indexes();
          for (const bsoncxx::document::view& index : cursor)
          {
            indexes.push_back(bsoncxx::document::value(index));
          }
        }
        catch (mongocxx::operation_exception& e)
        {
          if (e.code().value() != 26 /* NamespaceNotFound */)
          {
            MongoDBDatabase::ThrowException(e);
          }
        }
        catch (mongocxx::exception& e)
        {
          MongoDBDatabase::ThrowException(e);
        }

        return indexes;
      }

    public:
      explicit ExistingIndexes(mongocxx::database& database) :
        database_(database)
      {
      }

      bool Contains(const IndexDefinition& definition)
      {
        const std::vector<bsoncxx::document::value>& indexes = GetCollection(definition.collection_);

        for (size_t i = 0; i < indexes.size(); i++)
        {
          const bsoncxx::document::view index = indexes[i].view();
          bsoncxx::document::element keys = index["key"];

          if (keys &&
              keys.type() == bsoncxx::type::k_document &&
              HasSameKeys(keys.get_document().value, definition.keys_.view()) &&
              (!definition.unique_ || IsUniqueIndex(index)))
          {
            return true;
          }
        }

        return false;
      }
    };


    /**
     * The lock document of the schema upgrades, as a lease: a thread
     * renews it while the upgrade runs, so that the lock of an Orthanc
     * that crashed expires after "LEASE" milliseconds. The same thread
     * logs the progress of the index builds.
     **/
    class SchemaLock : public boost::noncopyable
    {
    private:
      static constexpr int64_t LEASE = 60000;         // Milliseconds
      static constexpr unsigned int RENEWAL = 10;     // Seconds
      static constexpr unsigned int PROGRESS = 30;    // Seconds

      MongoDBDatabase&       database_;
      std::string            owner_;
      std::atomic<bool>      done_;
      mongocxx::pool::entry  keeperClient_;  // The client of "keeper_"
      boost::thread          keeper_;

      static mongocxx::pipeline GetLease(const std::string& owner)
      {
        mongocxx::pipeline pipeline;
        pipeline.add_fields(make_document(
                              kvp("owner", owner),
                              kvp("expiresAt", make_document(kvp("$add", make_array("$$NOW", LEASE))))));
        return pipeline;
      }

      bool TryAcquire()
      {
        /**
         * Takes the lock if it is missing or expired, in one atomic
         * upsert (a missing "expiresAt" is less than any date). The
         * upsert cannot filter on "$expr", hence the "$cond".
         **/
        const bsoncxx::document::value isFree = make_document(
          kvp("$lt", make_array("$expiresAt", "$$NOW")));

        mongocxx::pipeline pipeline;
        pipeline.add_fields(make_document(
                              kvp("owner", make_document(kvp("$cond", make_array(isFree.view(), owner_, "$owner")))),
                              kvp("expiresAt", make_document(kvp("$cond", make_array(
                                                                   isFree.view(),
                                                                   make_document(kvp("$add", make_array("$$NOW", LEASE))),
                                                                   "$expiresAt"))))));

        mongocxx::options::find_one_and_update options;
        options.upsert(true);
        options.return_document(mongocxx::options::return_document::k_after);

        try
        {
          std::optional<bsoncxx::document::value> lock = database_.GetDatabase()["Locks"].find_one_and_update(
            make_document(kvp("_id", "SchemaUpgrade")), pipeline, options);

          return (lock &&
                  lock->view()["owner"] &&
                  lock->view()["owner"].type() == bsoncxx::type::k_string &&
                  lock->view()["owner"].get_string().value == owner_);
        }
        catch (mongocxx::exception& e)
        {
          MongoDBDatabase::ThrowException(e);
        }
      }

      static void LogIndexBuilds(mongocxx::client& client,
                                 const std::string& databaseName)
      {
        try
        {
          bsoncxx::document::value reply = client["admin"].run_command(make_document(
            kvp("currentOp", true),
            kvp("command.createIndexes", make_document(kvp("$exists", true))),
            kvp("ns", make_document(kvp("$regex", "^" + databaseName + "\\.")))));

          bsoncxx::document::element operations = reply.view()["inprog"];
          if (operations && operations.type() == bsoncxx::type::k_array)
          {
            for (const bsoncxx::array::element& operation : operations.get_array().value)
            {
              if (operation.type() == bsoncxx::type::k_document &&
                  operation["msg"] &&
                  operation["msg"].type() == bsoncxx::type::k_string)
              {
                LOG(WARNING) << "MongoDB: " << operation["ns"].get_string().value << ": "
                             << operation["msg"].get_string().value;
              }
            }
          }
        }
        catch (mongocxx::exception&)
        {
          // The user may not be allowed to run "currentOp": no progress then
        }
      }

      static void Keeper(SchemaLock* that)
      {
        mongocxx::client& client = *that->keeperClient_;
        const std::string databaseName = that->database_.GetDatabaseName();
        unsigned int elapsed = 0;

        while (!that->done_)
        {
          boost::this_thread::sleep(boost::posix_time::milliseconds(100));
          elapsed++;

          if (elapsed % (RENEWAL * 10) == 0)
          {
            try
            {
              client[databaseName]["Locks"].update_one(
                make_document(kvp("_id", "SchemaUpgrade"), kvp("owner", that->owner_)),
                GetLease(that->owner_));
            }
            catch (mongocxx::exception& e)
            {
              LOG(ERROR) << "MongoDB: cannot renew the lock of the schema upgrade: " << e.what();
            }
          }

          if (elapsed % (PROGRESS * 10) == 0)
          {
            LogIndexBuilds(client, databaseName);
          }
        }
      }

    public:
      explicit SchemaLock(MongoDBDatabase& database) :
        database_(database),
        owner_(Orthanc::Toolbox::GenerateUuid()),
        done_(false),
        keeperClient_(database.AcquireClient())
      {
        unsigned int waited = 0;

        while (!TryAcquire())
        {
          if (waited % 30 == 0)
          {
            LOG(WARNING) << "MongoDB: waiting for another Orthanc to finish upgrading the database";
          }

          boost::this_thread::sleep(boost::posix_time::seconds(1));
          waited++;
        }

        keeper_ = boost::thread(Keeper, this);
      }

      ~SchemaLock()
      {
        done_ = true;

        if (keeper_.joinable())
        {
          keeper_.join();
        }

        keeperClient_ = nullptr;

        try
        {
          database_.GetDatabase()["Locks"].delete_one(
            make_document(kvp("_id", "SchemaUpgrade"), kvp("owner", owner_)));
        }
        catch (mongocxx::exception& e)
        {
          LOG(ERROR) << "MongoDB: cannot release the lock of the schema upgrade (it expires by itself): "
                     << e.what();
        }
      }
    };
  }


  static int64_t EstimateDocumentsCount(mongocxx::database& database,
                                        const std::string& collection)
  {
    try
    {
      return database[collection].estimated_document_count();
    }
    catch (mongocxx::exception&)
    {
      return -1;
    }
  }


  bool MongoDBSchema::CreateIndexes(std::list<std::string>& missing,
                                    DatabaseManager& manager)
  {
    // The schema never runs inside a transaction, so the driver is used directly
    mongocxx::database database = MongoDBDatabase::GetDatabase(manager).GetDatabase();
    ExistingIndexes existing(database);

    missing.clear();

    const std::vector<IndexDefinition> indexes = GetIndexes();

    for (size_t i = 0; i < indexes.size(); i++)
    {
      const IndexDefinition& index = indexes[i];

      if (existing.Contains(index))
      {
        continue;
      }

      const int64_t count = EstimateDocumentsCount(database, index.collection_);
      if (count > 0)
      {
        LOG(WARNING) << "MongoDB: building the index " << index.GetDescription()
                     << " (about " << count << " documents), this can take a while";
      }

      bsoncxx::builder::basic::document options;
      options.append(kvp("name", index.GetName()));
      if (index.unique_)
      {
        options.append(kvp("unique", true));
      }

      const boost::posix_time::ptime start = boost::posix_time::microsec_clock::universal_time();

      try
      {
        database[index.collection_].create_index(index.keys_.view(), options.view());
      }
      catch (mongocxx::operation_exception& e)
      {
        if (index.unique_ &&
            e.code().value() == 11000 /* DuplicateKey */)
        {
          LOG(WARNING) << "MongoDB: the unique index " << index.GetDescription()
                       << " cannot be built, because of duplicates in the database: " << e.what();
          LOG(WARNING) << "MongoDB: run \"Resources/MongoDB/Upgrades/AuditDuplicates.js\" to list them, "
                       << "and \"RepairDuplicates.js\" to repair them";
          missing.push_back(index.GetDescription());
          continue;
        }
        else
        {
          MongoDBDatabase::ThrowException(e);
        }
      }
      catch (mongocxx::exception& e)
      {
        MongoDBDatabase::ThrowException(e);
      }

      if (count > 0)
      {
        LOG(WARNING) << "MongoDB: the index " << index.GetDescription() << " is built ("
                     << (boost::posix_time::microsec_clock::universal_time() - start).total_seconds() << "s)";
      }
    }

    return missing.empty();
  }


  bool MongoDBSchema::CheckIndexes(std::list<std::string>& missing,
                                   DatabaseManager& manager)
  {
    mongocxx::database database = MongoDBDatabase::GetDatabase(manager).GetDatabase();
    ExistingIndexes existing(database);

    missing.clear();

    const std::vector<IndexDefinition> indexes = GetIndexes();

    for (size_t i = 0; i < indexes.size(); i++)
    {
      if (!existing.Contains(indexes[i]))
      {
        missing.push_back(indexes[i].GetDescription());
      }
    }

    return missing.empty();
  }


  static bool LookupIntegerProperty(unsigned int& target,
                                    MongoDBGlobalProperties& properties,
                                    Orthanc::GlobalProperty property)
  {
    std::string value;

    if (properties.LookupGlobalProperty(value, MISSING_SERVER_IDENTIFIER, property))
    {
      try
      {
        target = boost::lexical_cast<unsigned int>(value);
        return true;
      }
      catch (boost::bad_lexical_cast&)
      {
        throw Orthanc::OrthancException(Orthanc::ErrorCode_Database,
                                        "Corrupted global property " + std::to_string(property) + ": " + value);
      }
    }
    else
    {
      return false;
    }
  }


  static void LogMissingIndexes(const std::list<std::string>& missing)
  {
    for (std::list<std::string>::const_iterator it = missing.begin(); it != missing.end(); ++it)
    {
      LOG(WARNING) << "MongoDB: missing index " << *it;
    }
  }


  /**
   * "AuditLogsRetentionDays" makes the index { ts } of "AuditLogs" a TTL
   * index, so that the server deletes the older logs. Setting it back
   * to 0 rebuilds the index without TTL: nothing is ever deleted unless
   * the option is set.
   **/
  static void ConfigureAuditLogsRetention(mongocxx::database& database,
                                          unsigned int days)
  {
    const bsoncxx::document::value keys = make_document(kvp("ts", 1));

    try
    {
      std::optional<bsoncxx::document::value> index;

      for (const bsoncxx::document::view& existing : database["AuditLogs"].list_indexes())
      {
        if (existing["key"] &&
            existing["key"].type() == bsoncxx::type::k_document &&
            HasSameKeys(existing["key"].get_document().value, keys.view()))
        {
          index = bsoncxx::document::value(existing);
        }
      }

      if (!index)
      {
        if (days > 0)
        {
          LOG(WARNING) << "MongoDB: the index AuditLogs.ts_1 is missing, \"AuditLogsRetentionDays\" has no effect";
        }

        return;
      }

      const bsoncxx::document::element current = index->view()["expireAfterSeconds"];
      const int64_t expected = static_cast<int64_t>(days) * 24 * 3600;

      if (days > 0)
      {
        int64_t seconds = -1;
        if (current)
        {
          switch (current.type())
          {
            case bsoncxx::type::k_int32:
              seconds = current.get_int32().value;
              break;

            case bsoncxx::type::k_int64:
              seconds = current.get_int64().value;
              break;

            case bsoncxx::type::k_double:
              seconds = static_cast<int64_t>(current.get_double().value);
              break;

            default:
              break;
          }
        }

        if (seconds != expected)
        {
          database.run_command(make_document(
            kvp("collMod", "AuditLogs"),
            kvp("index", make_document(kvp("keyPattern", keys.view()), kvp("expireAfterSeconds", expected)))));
          LOG(WARNING) << "MongoDB: the audit logs are deleted after " << days << " days";
        }
      }
      else if (current)
      {
        const std::string name(index->view()["name"].get_string().value);
        database["AuditLogs"].indexes().drop_one(name);
        database["AuditLogs"].create_index(keys.view(), make_document(kvp("name", name)));
        LOG(WARNING) << "MongoDB: the audit logs are not deleted automatically anymore";
      }
    }
    catch (mongocxx::operation_exception& e)
    {
      if (e.code().value() != 26 /* NamespaceNotFound */)
      {
        MongoDBDatabase::ThrowException(e);
      }
    }
    catch (mongocxx::exception& e)
    {
      MongoDBDatabase::ThrowException(e);
    }
  }


  static void Upgrade(DatabaseManager& manager,
                      const MongoDBParameters& parameters)
  {
    MongoDBDatabase& database = MongoDBDatabase::GetDatabase(manager);
    MongoDBGlobalProperties properties(manager);

    SchemaLock lock(database);

    unsigned int value;
    if (!LookupIntegerProperty(value, properties, Orthanc::GlobalProperty_DatabaseSchemaVersion))
    {
      properties.SetGlobalProperty(MISSING_SERVER_IDENTIFIER, Orthanc::GlobalProperty_DatabaseSchemaVersion,
                                   std::to_string(MongoDBSchema::SCHEMA_VERSION).c_str());
    }

    // A database without revision was created by a previous version of the plugin, or is empty
    unsigned int revision;
    if (!LookupIntegerProperty(revision, properties, Orthanc::GlobalProperty_DatabasePatchLevel))
    {
      revision = 1;
    }

    std::list<std::string> missing;
    bool complete;

    if (parameters.IsCreateIndexesAtStartup())
    {
      complete = MongoDBSchema::CreateIndexes(missing, manager);
    }
    else
    {
      complete = MongoDBSchema::CheckIndexes(missing, manager);
      if (!complete)
      {
        LogMissingIndexes(missing);
        LOG(WARNING) << "MongoDB: \"CreateIndexesAtStartup\" is false, build the missing indexes offline "
                     << "with \"Resources/MongoDB/Upgrades/CreateIndexes.js\"";
      }
    }

    if (revision > MongoDBSchema::SCHEMA_REVISION)
    {
      LOG(WARNING) << "MongoDB: the database has the schema revision " << revision
                   << ", it was upgraded by a more recent version of this plugin";
    }
    else if (complete)
    {
      if (revision < MongoDBSchema::SCHEMA_REVISION)
      {
        LOG(WARNING) << "MongoDB: upgrading the database from the schema revision " << revision
                     << " to " << MongoDBSchema::SCHEMA_REVISION;
      }

      revision = MongoDBSchema::SCHEMA_REVISION;
    }
    else if (revision == MongoDBSchema::SCHEMA_REVISION)
    {
      // Some index was dropped from outside the plugin
      LOG(WARNING) << "MongoDB: some indexes of the schema revision " << revision << " are missing";
    }
    else
    {
      LOG(WARNING) << "MongoDB: the database stays at the schema revision " << revision
                   << " until all the indexes of revision " << MongoDBSchema::SCHEMA_REVISION << " exist; "
                   << "without its unique indexes, concurrent writes on a standalone server can create duplicates";
    }

    properties.SetGlobalProperty(MISSING_SERVER_IDENTIFIER, Orthanc::GlobalProperty_DatabasePatchLevel,
                                 std::to_string(revision).c_str());

    // A new database needs no full scan to compute its statistics
    MongoDBStatistics(manager).InitializeIfEmpty();

    mongocxx::database driver = database.GetDatabase();
    ConfigureAuditLogsRetention(driver, parameters.GetAuditLogsRetentionDays());
  }


  void MongoDBSchema::Configure(DatabaseManager& manager,
                                const MongoDBParameters& parameters,
                                bool readOnly,
                                uint32_t expectedVersion)
  {
    if (expectedVersion != SCHEMA_VERSION)
    {
      LOG(ERROR) << "This database plugin is incompatible with your version of Orthanc "
                 << "expecting the DB schema version " << expectedVersion
                 << ", but this plugin is only compatible with version " << SCHEMA_VERSION;
      throw Orthanc::OrthancException(Orthanc::ErrorCode_Plugin);
    }

    MongoDBDatabase& database = MongoDBDatabase::GetDatabase(manager);
    MongoDBGlobalProperties properties(manager);

    if (!readOnly)
    {
      if (!database.IsWritablePrimary())
      {
        throw Orthanc::OrthancException(Orthanc::ErrorCode_Database,
                                        "The MongoDB server is not a writable primary");
      }

      Upgrade(manager, parameters);
    }

    unsigned int version = 0;
    if (!LookupIntegerProperty(version, properties, Orthanc::GlobalProperty_DatabaseSchemaVersion) ||
        version != SCHEMA_VERSION)
    {
      throw Orthanc::OrthancException(Orthanc::ErrorCode_Database,
                                      "MongoDB plugin is incompatible with database schema version: " +
                                      std::to_string(version));
    }

    // Every revision can be used, as they only differ by additions
    unsigned int revision = 0;
    if (!LookupIntegerProperty(revision, properties, Orthanc::GlobalProperty_DatabasePatchLevel))
    {
      throw Orthanc::OrthancException(Orthanc::ErrorCode_Database,
                                      "The MongoDB database has no schema revision, "
                                      "start a writable Orthanc once to initialize it");
    }

    if (readOnly &&
        revision < SCHEMA_REVISION)
    {
      LOG(WARNING) << "MongoDB: the database has the schema revision " << revision
                   << ", start a writable Orthanc once to upgrade it to " << SCHEMA_REVISION;
    }
  }
}
